// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvcsvsvwgelwewrjcokp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Y3N2c3Z3Z2Vsd2V3cmpjb2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDA5NTQsImV4cCI6MjA1OTE3Njk1NH0.H3dgMndTQeSbhdu4hfVnZCuF1FAorISXP1ppNriShpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);